sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: "12"
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run build
